- name: configure mysql server
  hosts: database
  become: yes  #this is for remote server sudo access 
  vars_files:
   - /var/expense/credentials_mysql.yml #but this placed in ansible server
  roles:
   - mysql # it will go to role folder and check for mysql and it will load all from there