- name: install nginx server
  ansible.builtin.package:
    name: nginx
    state: present

- name: start and enable service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: import task from common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app_pre_req

# - name: Remove the default content that web server is serving
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: absent

# - name: create directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory

# - name: downlaod frontend code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /tmp/frontend.zip

# - name: extract the content
#   ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

- name: copy expense conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
    - Restart nginx   #it will check in handlers folder
